project:
  type: website
  output-dir: docs

website:
  title: "Classical and Bayesian Linear Regression"
  description: "Notes and Quarto demonstrations comparing classical, conjugate Bayesian, and spike-and-slab regression models."
  navbar:
    left:
      - text: "Home"
        href: index.html
      - text: "Notes"
        href: notes.html
      - text: "Classical Regression"
        href: classical_linear_regression_simulation.html
      - text: "Bayesian (Gaussian Prior)"
        href: bayesian_linear_regression_conjugate.html
      - text: "Bayesian (Spike & Slab)"
        href: bayesian_spike_and_slab.html

format:
  html:
    theme: flatly
    toc: true
    code-fold: true
    highlight-style: github

author:
  - name: "Peter Sørensen"
    affiliation:
      - "Center for Quantitative Genetics and Genomics"
      - "Aarhus University"
