project:
  type: website
  output-dir: docs
  resources:
    - narration/**

website:
  title: "Bayesian Linear Regression"
  description: "Notes and Quarto demonstrations comparing classical, conjugate Bayesian, and spike-and-slab regression models."
  navbar:
    left:
      - text: "Home"
        href: index.html
      - text: "Notes"
        href: notes.html
      - text: "BLR slides"
        href: bayesian_linear_regression_slides.html
      - text: "GSEA slides"
        href: bayesian_gene_set_slides.html
      - text: "Classical Regression tutorial"
        href: classical_linear_regression_simulation.html
      - text: "Bayesian (Gaussian Prior) tutorial"
        href: bayesian_linear_regression_conjugate.html
      - text: "Bayesian (Spike & Slab) tutorial"
        href: bayesian_spike_and_slab.html
      - text: "Bayesian MAGMA tutorial"
        href: bayesian_magma_tutorial.html

format:
  html:
    embed-resources: true
    theme: flatly
    toc: false
    code-fold: true
    highlight-style: github

author:
  - name: "Palle Duun Rohde"
    affiliation:
      - "Genomic Medicine, Department of Health Science and Technology, Aalborg University, Denmark"
  - name: "Peter Sørensen"
    affiliation:
      - "Center for Quantitative Genetics and Genomics, Aarhus University, Denmark"
